apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-strategy-artifacts
  namespace: f1-strategy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-strategy-data
  namespace: f1-strategy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
