apiVersion: v1
kind: Service
metadata:
  name: f1-strategy-api
  namespace: f1-strategy
  labels:
    app: f1-strategy-api
spec:
  selector:
    app: f1-strategy-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: f1-strategy-api-metrics
  namespace: f1-strategy
  labels:
    app: f1-strategy-api
spec:
  selector:
    app: f1-strategy-api
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
